"""add links and click tables

Revision ID: f8d20dac2260
Revises:
Create Date: 2026-09-26 03:00:53.712027
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f8d20dac2260"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_ip", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "click_daily",
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("country", sa.String(length=2), server_default="??", nullable=False),
        sa.Column("referrer_host", sa.String(length=255), server_default="direct", nullable=False),
        sa.Column("clicks", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["link_id"], ["links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("link_id", "day", "country", "referrer_host"),
    )
    op.create_table(
        "click_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("link_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "clicked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("referrer_host", sa.String(length=255), nullable=True),
        sa.Column("ua_family", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["link_id"], ["links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_click_events_link_time", "click_events", ["link_id", "clicked_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_click_events_link_time", table_name="click_events")
    op.drop_table("click_events")
    op.drop_table("click_daily")
    op.drop_table("links")
    # ### end Alembic commands ###
